# Generated by Django 5.0.3 on 2026-10-03 04:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(help_text='Unique student registration number or ID', max_length=50, unique=True, verbose_name='Student ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Full Name')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10, verbose_name='Gender')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('department', models.CharField(help_text='e.g., Computer Science, Grade 10-A', max_length=100, verbose_name='Department / Class')),
                ('date_joined', models.DateField(default=django.utils.timezone.now, verbose_name='Date Joined')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Course/Class Name')),
                ('code', models.CharField(help_text='e.g., CS101, MATH201', max_length=30, unique=True, verbose_name='Course Code')),
                ('teacher', models.CharField(max_length=120, verbose_name='Teacher / Lecturer')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('students', models.ManyToManyField(blank=True, help_text='Select students enrolled in this course (optional)', related_name='courses', to='attendance.student', verbose_name='Enrolled Students')),
            ],
            options={
                'verbose_name': 'Course / Class',
                'verbose_name_plural': 'Courses / Classes',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date')),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Late', 'Late')], default='Present', max_length=10, verbose_name='Status')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.course', verbose_name='Course / Class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='attendance.student', verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-date', 'course__code', 'student__full_name'],
                'unique_together': {('student', 'course', 'date')},
            },
        ),
    ]
